### ISSUE TITLE
How to solve the problem of ReferenceError: self is not defined?

### ISSUE THREAD

**Issue by shelley-xl** [DIYgod/DPlayer#1341]
Normal development environment
Build error

building client + server bundles...
build error:
ReferenceError: self is not defined
    at Object.<anonymous> (D:\_GitHub\www\node_modules\dplayer\dist\DPlayer.min.js:1:206)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async build (file:///D:/_GitHub/www/node_modules/vitepress/dist/node/serve-d5608de4.js:41740:24)

**Comment by DIYgod** [comment]
Please add a minimal reproduction so we can investigate.
