### ISSUE TITLE
Mayday,Mayday,Mayday! How to use danmaku? (求助，如何使用弹幕)

### ISSUE THREAD

**Issue by GilelsPrice** [DIYgod/DPlayer#19]
As Title
如题
How to use your danmaku api or build an api all by myself?
如何使用你的弹幕API或自己搭建一个API?
And How To Manage Danmaku?
并且如何管理弹幕?
Thank you;
谢谢你;

**Comment by DIYgod** [comment]
Use and build an api: 
As README

Manage Danmaku: 
1. Use my api: can't
2. Build api yourself: use [mongo express](https://github.com/mongo-express/mongo-express)

**Comment by GilelsPrice** [comment]
Thank you,

**Comment by GilelsPrice** [comment]
How To Fix
`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (/var/lib/openshift/57b575697628e1210d0002d4/app-root/runtime/repo/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/var/lib/openshift/57b575697628e1210d0002d4/app-root/runtime/repo/index.js:12:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
`
![image](https://cloud.githubusercontent.com/assets/18818952/17768780/437a1dec-6568-11e6-8da5-7454dd1bba74.png)

**Comment by DIYgod** [comment]
It seems to be port conflict.

Use other port or proxy with nginx.

**Comment by GilelsPrice** [comment]
I found the problom;
I try to build it on `openshift`
So,I change `index.js`
```node
var express = require('express');
var logger = require('./tools/logger');
require('./tools/mongodb');

logger.info('🍻 DPlayer start! Cheers!');
var server_port = process.env.OPENSHIFT_NODEJS_PORT || 8080
var server_ip_address = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1'
var app = express();
app.all('*', require('./routes/all'));
app.get('/', require('./routes/get'));
app.post('/', require('./routes/post'));
app.get('/list', require('./routes/list'));
app.listen(server_port, server_ip_address);
```
At last,Thank for your anwser
Have a Nice Day!
